[package]
name = "tcp-listener"
version = "0.1.0"
authors = ["jelipo <me@jelipo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.5"
fantasy-util = "0.1.6"